http:
  host: "0.0.0.0"
  port: "8081"

mllp_v2_2:
  host: "0.0.0.0"
  port: "8022"
  
mllp_v2_3:
  host: "0.0.0.0"
  port: "8023"

salesforce:
  username: "mounish.karandla-wgbc@force.com"
  url: "https://login.salesforce.com/services/Soap/u/47.0" 
  consumerKey: "3MVG9fe4g9fhX0E7pow78dTuRuJHJCj8ultqjggSPPqoqprPCGlZ2fSzi4Q.dJKdwymAvLS0Lu4rCOTsSYSz4"
  consumerSecret: "07218BF4B2BB2E782735CAC8496E2A2408F1212F60E725ECE1378D88DE0932B9"
anypoint:
  mq:
    client_id: "2534b6b2f1a8444d89812ab983b40aef"
  
until:
  successful:
    maxretries: "3"
    timebetween: "3000"